// <auto-generated />
namespace PotatoCatalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _121215RemovedBoolAddedOrderStatusEnumtoOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_121215RemovedBoolAddedOrderStatusEnumtoOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201512122019250_12-12-15-RemovedBoolAddedOrderStatusEnum-toOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
