// <auto-generated />
namespace PotatoCatalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedcroppedImagefromGame : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedcroppedImagefromGame));
        
        string IMigrationMetadata.Id
        {
            get { return "201512011903429_removed-croppedImage-fromGame"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
