// <auto-generated />
namespace PotatoCatalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcroppedImagePathtoGame : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcroppedImagePathtoGame));
        
        string IMigrationMetadata.Id
        {
            get { return "201512011146066_added-croppedImagePath-toGame"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
